apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: webapi-routing
  namespace: my-web-api
spec:
  rules:
  - host: webapi-test.skuba.eu
    http:
      paths:
      - backend:
          serviceName: my-web-api
          servicePort: 8089