apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-web-app
spec:
  selector:
    matchLabels:
      run: my-web-app
  replicas: 2
  template:
    metadata:
      labels:
        run: my-web-app
    spec:
      containers:
      - name: my-web-app
        image: romanas/web-api:5.0
        ports:
        - containerPort: 80