apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-web-api
spec:
  selector:
    matchLabels:
      run: my-web-api
  replicas: 2
  template:
    metadata:
      labels:
        run: my-web-api
    spec:
      containers:
      - name: my-web-api
        image: romanas/web-api:latest
        ports:
          - containerPort: 80
            name: http-web-api
        env:
          - name: ASPNETCORE_URLS
            value: http://+:80