apiVersion: v1
kind: Service
metadata:
  name: web-api
  labels:
    run: my-web-api
spec:
  selector:
    run: my-web-api
  ports:
  - port: 8089
    protocol: TCP
    targetPort: 80
    nodePort: 30010
  type: NodePort