apiVersion: apps/v1
kind: Deployment
metadata:
  name: listener-app
spec:
  selector:
    matchLabels:
      run: listener-app
  replicas: 1
  template:
    metadata:
      labels:
        run: listener-app
    spec:
      containers:
      - name: listener-app
        image: romanas/listener-app:1.1.1675