apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-sync-app
spec:
  selector:
    matchLabels:
      run: data-sync-app
  replicas: 2
  template:
    metadata:
      labels:
        run: data-sync-app
    spec:
      containers:
      - name: data-sync-app
        image: romanas/data-sync-app:1.1.1675